title: Hugo demo language redirect

# Language configuration
defaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
  de:
    contentDir: content/de
    languageName: Deutsch
    weight: 2
  fr:
    contentDir: content/fr
    languageName: Fran√ßais
    weight: 3

#
# Handle netlify redirects on root page (home)
#
# 1.) add redirects/headers
outputs:
  home:
    - html
    - redirects

# 2.) remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes: [""]

# 3.) add output formats for netlify
outputFormats:
  redirects:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
